<a href="https://cognitiveclass.ai"><img src = "https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/Logos/organization_logo/organization_logo.png" width = 400> </a>

<h1 align=center><font size = 5>Peer Review Final Assignment</font></h1>

## Introduction


In this lab, you will build an image classifier using the VGG16 pre-trained model, and you will evaluate it and compare its performance to the model we built in the last module using the ResNet50 pre-trained model. Good luck!

## Table of Contents

<div class="alert alert-block alert-info" style="margin-top: 20px">

<font size = 3>    

1. <a href="#item41">Download Data 
2. <a href="#item42">Part 1</a>
3. <a href="#item43">Part 2</a>  
4. <a href="#item44">Part 3</a>  

</font>
    
</div>

<a id="item41"></a>

## Download Data

Use the <code>wget</code> command to download the data for this assignment from here: https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0321EN/data/concrete_data_week4.zip

Use the following cells to download the data.

In [ ]:
!wget 'https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0321EN/data/concrete_data_week4.zip'

--2020-03-31 20:52:06--  https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0321EN/data/concrete_data_week4.zip
67.228.254.196pi.us-geo.objectstorage.softlayer.net (s3-api.us-geo.objectstorage.softlayer.net)... 
Connecting to s3-api.us-geo.objectstorage.softlayer.net (s3-api.us-geo.objectstorage.softlayer.net)|67.228.254.196|:443... connected.
200 OKequest sent, awaiting response... 
Length: 261483817 (249M) [application/zip]
Saving to: ‘concrete_data_week4.zip’

concrete_data_week4 100%[===================>] 249.37M  42.9MB/s    in 6.1s    

2020-03-31 20:52:14 (40.7 MB/s) - ‘concrete_data_week4.zip’ saved [261483817/261483817]



In [ ]:
!unzip -o concrete_data_week4.zip

  inflating: concrete_data_week4/train/negative/06407.jpg  
  inflating: __MACOSX/concrete_data_week4/train/negative/._06407.jpg  
  inflating: concrete_data_week4/train/negative/09052.jpg  
  inflating: __MACOSX/concrete_data_week4/train/negative/._09052.jpg  
  inflating: concrete_data_week4/train/negative/06361.jpg  
  inflating: __MACOSX/concrete_data_week4/train/negative/._06361.jpg  
  inflating: concrete_data_week4/train/negative/00710.jpg  
  inflating: __MACOSX/concrete_data_week4/train/negative/._00710.jpg  
  inflating: concrete_data_week4/train/negative/10503.jpg  
  inflating: __MACOSX/concrete_data_week4/train/negative/._10503.jpg  
  inflating: concrete_data_week4/train/negative/04576.jpg  
  inflating: __MACOSX/concrete_data_week4/train/negative/._04576.jpg  
  inflating: concrete_data_week4/train/negative/14765.jpg  
  inflating: __MACOSX/concrete_data_week4/train/negative/._14765.jpg  
  inflating: concrete_data_week4/train/negative/03219.jpg  
  inflating: __MACOSX/c

After you unzip the data, you fill find the data has already been divided into a train, validation, and test sets.

<a id="item42"></a>

## Part 1

In this part, you will design a classifier using the VGG16 pre-trained model. Just like the ResNet50 model, you can import the model <code>VGG16</code> from <code>keras.applications</code>.

You will essentially build your classifier as follows:
1. Import libraries, modules, and packages you will need. Make sure to import the *preprocess_input* function from <code>keras.applications.vgg16</code>.
2. Use a batch size of 100 images for both training and validation.
3. Construct an ImageDataGenerator for the training set and another one for the validation set. VGG16 was originally trained on 224 × 224 images, so make sure to address that when defining the ImageDataGenerator instances.
4. Create a sequential model using Keras. Add VGG16 model to it and dense layer.
5. Compile the mode using the adam optimizer and the categorical_crossentropy loss function.
6. Fit the model on the augmented data using the ImageDataGenerators.

Use the following cells to create your classifier.

In [ ]:
!pip install tensorflow

You should consider upgrading via the '/opt/venv/bin/python3 -m pip install --upgrade pip' command.


In [3]:
from keras.preprocessing.image import ImageDataGenerator

import keras
from keras.models import Sequential
from keras.layers import Dense

from keras.applications import vgg16
from keras.applications.vgg16 import preprocess_input

In [4]:
num_classes = 2

image_resize = 224

batch_size_training = 100
batch_size_validation = 100


In [10]:
data_generator = ImageDataGenerator(
    preprocessing_function=preprocess_input,
)
train_generator = data_generator.flow_from_directory(
    'concrete_data_week4/train',
    target_size=(image_resize, image_resize),
    batch_size=batch_size_training,
    class_mode='categorical')

validation_generator = data_generator.flow_from_directory(
    'concrete_data_week4/valid',
    target_size=(image_resize, image_resize),
    batch_size=batch_size_training,
    class_mode='categorical')


Found 30001 images belonging to 2 classes.
Found 9501 images belonging to 2 classes.


In [4]:
model = Sequential()

model.add(vgg16.VGG16(
    include_top=False,
    pooling='avg',
    weights='imagenet',
    ))

model.add(Dense(num_classes, activation='softmax'))
model.layers[0].trainable = False

58892288/58889256 [==============================] - 1s 0us/step


In [5]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
vgg16 (Model)                (None, 512)               14714688  
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 1026      
Total params: 14,715,714
Trainable params: 1,026
Non-trainable params: 14,714,688
_________________________________________________________________


In [6]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [7]:
steps_per_epoch_training = len(train_generator)
steps_per_epoch_validation = len(validation_generator)
num_epochs = 2

In [ ]:
!pip install pillow

     |████████████████████████████████| 2.1 MB 3.4 MB/s eta 0:00:01
You should consider upgrading via the '/opt/venv/bin/python3 -m pip install --upgrade pip' command.


In [8]:
import sys
from PIL import Image
sys.modules['Image'] = Image

In [9]:
from PIL import Image
print(Image.__file__)

/opt/venv/lib/python3.7/site-packages/PIL/Image.py


In [10]:
import Image
print(Image.__file__)

/opt/venv/lib/python3.7/site-packages/PIL/Image.py


In [0]:
fit_history = model.fit_generator(
    train_generator,
    steps_per_epoch=steps_per_epoch_training,
    epochs=num_epochs,
    validation_data=validation_generator,
    validation_steps=steps_per_epoch_validation,
    verbose=1
)

Epoch 1/2
301/301 [==============================] - 17003s 56s/step - loss: 0.0822 - accuracy: 0.9738 - val_loss: 0.0258 - val_accuracy: 0.9949
Epoch 2/2
 60/301 [====>.........................] - ETA: 2:42:39 - loss: 0.0212 - accuracy: 0.9947

 63/301 [=====>........................] - ETA: 2:41:10 - loss: 0.0210 - accuracy: 0.9950

 70/301 [=====>........................] - ETA: 2:37:14 - loss: 0.0208 - accuracy: 0.9952

 75/301 [======>.......................] - ETA: 2:34:06 - loss: 0.0207 - accuracy: 0.9954

155/301 [==============>...............] - ETA: 1:41:57 - loss: 0.0192 - accuracy: 0.9957

301/301 [==============================] - 17406s 58s/step - loss: 0.0179 - accuracy: 0.9958 - val_loss: 0.0131 - val_accuracy: 0.9967


In [12]:
model.save('classifier_vgg16_model.h5')

<a id="item43"></a>

## Part 2

In this part, you will evaluate your deep learning models on a test data. For this part, you will need to do the following:

1. Load your saved model that was built using the ResNet50 model. 
2. Construct an ImageDataGenerator for the test set. For this ImageDataGenerator instance, you only need to pass the directory of the test images, target size, and the **shuffle** parameter and set it to False.
3. Use the **evaluate_generator** method to evaluate your models on the test data, by passing the above ImageDataGenerator as an argument. You can learn more about **evaluate_generator** [here](https://keras.io/models/sequential/).
4. Print the performance of the classifier using the VGG16 pre-trained model.
5. Print the performance of the classifier using the ResNet pre-trained model.


Use the following cells to evaluate your models.

In [1]:
from keras.applications import ResNet50
from keras.applications.resnet50 import preprocess_input

from keras.models import load_model

model_50 = load_model('classifier_resnet_model.h5')

Using TensorFlow backend.
/opt/venv/lib/python3.7/site-packages/keras/engine/saving.py:384: UserWarning: Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
  warnings.warn('Error in loading the saved optimizer '


In [5]:
data_generator_50 = ImageDataGenerator(
    preprocessing_function=preprocess_input
)
batch_size_test = 100
test_generator = data_generator_50.flow_from_directory(
    'concrete_data_week4/test',
    shuffle= False,
    target_size=(image_resize, image_resize),
    batch_size=batch_size_test,
    class_mode='categorical')




Found 500 images belonging to 2 classes.


In [6]:
eval_history = model_50.evaluate_generator(
    test_generator,
    verbose=1
)

eval_history

5/5 [==============================] - 130s 26s/step


[0.4817318022251129, 0.9039999842643738]

In [7]:
model = load_model('classifier_vgg16_model.h5')

/opt/venv/lib/python3.7/site-packages/keras/engine/saving.py:384: UserWarning: Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
  warnings.warn('Error in loading the saved optimizer '


In [8]:
print("VGG16:")
eval_history_16 = model.evaluate_generator(test_generator,verbose=1)
eval_history_16

VGG16:
5/5 [==============================] - 190s 38s/step


[0.008442923426628113, 0.9980000257492065]

In [9]:
print("VGG16:")
print(model.metrics_names)
print(eval_history_16)

print("ResNet50:")
print(model_50.metrics_names)
print(eval_history)

VGG16:
['loss', 'accuracy']
[0.008442923426628113, 0.9980000257492065]
ResNet50:
['loss', 'accuracy']
[0.4817318022251129, 0.9039999842643738]


<a id="item44"></a>

## Part 3

In this model, you will predict whether the images in the test data are images of cracked concrete or not. You will do the following:

1. Use the **predict_generator** method to predict the class of the images in the test data, by passing the test data ImageDataGenerator instance defined in the previous part as an argument. You can learn more about the **predict_generator** method [here](https://keras.io/models/sequential/).
2. Report the class predictions of the first five images in the test set. You should print something list this:

<center>
    <ul style="list-style-type:none">
        <li>Positive</li>  
        <li>Negative</li> 
        <li>Positive</li>
        <li>Positive</li>
        <li>Negative</li>
    </ul>
</center>

Use the following cells to make your predictions.

In [11]:
import numpy as np

test_generator_50 = data_generator_50.flow_from_directory(
    'concrete_data_week4/test',
    shuffle= False,
    target_size=(image_resize, image_resize),
    batch_size=batch_size_test,
    class_mode='categorical')
prediction_50=model.predict_generator(test_generator_50)

test_generator = data_generator.flow_from_directory(
    'concrete_data_week4/test',
    shuffle= False,
    target_size=(image_resize, image_resize),
    batch_size=batch_size_test,
    class_mode='categorical')
prediction=model.predict_generator(test_generator)

Found 500 images belonging to 2 classes.
Found 500 images belonging to 2 classes.


In [15]:
prediction_50

array([[9.98426557e-01, 1.57345366e-03],
       [8.95825326e-01, 1.04174621e-01],
       [9.68615115e-01, 3.13848332e-02],
       [9.92082238e-01, 7.91779906e-03],
       [9.87321436e-01, 1.26785161e-02],
       [9.90951061e-01, 9.04891267e-03],
       [9.99245286e-01, 7.54688575e-04],
       [9.82447445e-01, 1.75525267e-02],
       [9.94199276e-01, 5.80078550e-03],
       [9.99715269e-01, 2.84688052e-04],
       [9.96895075e-01, 3.10490397e-03],
       [9.92546141e-01, 7.45387748e-03],
       [9.93021190e-01, 6.97883498e-03],
       [9.99543607e-01, 4.56306530e-04],
       [9.89780188e-01, 1.02197705e-02],
       [9.94371653e-01, 5.62834600e-03],
       [9.75380659e-01, 2.46193390e-02],
       [9.96250689e-01, 3.74928326e-03],
       [9.87524509e-01, 1.24754813e-02],
       [9.87223625e-01, 1.27763404e-02],
       [9.87895727e-01, 1.21042449e-02],
       [9.93637741e-01, 6.36221049e-03],
       [9.99504685e-01, 4.95294866e-04],
       [9.99751270e-01, 2.48718832e-04],
       [9.839206

In [12]:
#round float to 3 digit after dot, then slice first five element
result_50=prediction_50.round(3)[:5]
print(result_50)
result=prediction.round(3)[:5]
print(result)

[[0.998 0.002]
 [0.896 0.104]
 [0.969 0.031]
 [0.992 0.008]
 [0.987 0.013]]
[[0.998 0.002]
 [0.896 0.104]
 [0.969 0.031]
 [0.992 0.008]
 [0.987 0.013]]


In [13]:
ind =0
print("ResNet50")
for i in result_50:
    if result_50[ind][0]>result_50[ind][1]:
        print("Negative")
    else:
        print("Positive")
    ind= ind +1

ResNet50
Negative
Negative
Negative
Negative
Negative


In [14]:
ind =0
print("VGG16")
for i in result:
    if result[ind][0]>result[ind][1]:
        print("Negative")
    else:
        print("Positive")
    ind= ind +1

VGG16
Negative
Negative
Negative
Negative
Negative


### Thank you for completing this lab!

This notebook was created by Alex Aklson.

This notebook is part of a course on **Coursera** called *AI Capstone Project with Deep Learning*. If you accessed this notebook outside the course, you can take this course online by clicking [here](https://cocl.us/DL0321EN_Coursera_Week4_LAB1).

<hr>

Copyright &copy; 2020 [IBM Developer Skills Network](https://cognitiveclass.ai/?utm_source=bducopyrightlink&utm_medium=dswb&utm_campaign=bdu). This notebook and its source code are released under the terms of the [MIT License](https://bigdatauniversity.com/mit-license/).